version: "3.8"

services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    labels:
      - traefik.http.routers.adguard.rule=Host(`adguard.chuj`)
      - traefik.http.services.adguard.loadbalancer.server.port=80
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '9001:80/tcp'
      - '443:443/tcp'
      - '443:443/udp'
      - '3000:3000/tcp'
        #    network_mode: host
    volumes:
      - 'adguard-data:/opt/adguardhome/work'
      - 'adguard-config:/opt/adguardhome/conf'
    restart: unless-stopped

volumes:
  adguard-data:
  adguard-config:
