version: "3.7"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data portainer/portainer'
    restart: unless-stopped

  adguard:
    container_name: adguard
    image: adguard/adguardhome
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '68:68/tcp'
      - '68:68/udp'
      - '80:80/tcp'
      - '443:443/tcp'
      - '853:853/tcp'
      - '3000:3000/tcp'
    network_mode: host
    volumes:
      - 'adguard-data:/opt/adguardhome/work'
      - 'adguard-config:/opt/adguardhome/conf'
    restart: unless-stopped

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - SERVERURL=home.jwr.ski #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - 'wireguard-config:/config'
      - '/lib/modules:/lib/modules'
    ports:
      - 51820:51820/udp
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - transmission-config:/config
      - transmission-downloads:/downloads
      - transmission-watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

volumes:
    portainer_data:
    adguard-data:
    adguard-config:
    wireguard-config:
    transmission-config:
    transmission-downloads:
    transmission-watch:
