version: "3.8"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    labels:
      - traefik.http.routers.portainer.rule=Host(`portainer.lan`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data portainer/portainer'
    restart: unless-stopped

  adguard:
    container_name: adguard
    image: adguard/adguardhome
    labels:
      - traefik.http.routers.adguard.rule=Host(`adguard.lan`)
      - traefik.http.services.adguard.loadbalancer.server.port=80
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '9001:80/tcp'
      - '443:443/tcp'
      - '443:443/udp'
      - '3000:3000/tcp'
        #    network_mode: host
    volumes:
      - 'adguard-data:/opt/adguardhome/work'
      - 'adguard-config:/opt/adguardhome/conf'
    restart: unless-stopped

  reverse-proxy:
    container_name: traefik
    # The official v2 Traefik docker image
    image: traefik:v2.5
    labels:
      - traefik.http.routers.traefik.rule=Host(`traefik.lan`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  openbooks:
    container_name: openbooks
    image: evanbuss/openbooks
    labels:
      - traefik.http.routers.openbooks.rule=Host(`openbooks.lan`)
      - traefik.http.services.openbooks.loadbalancer.server.port=9002
    command: --persist
    ports:
      - "9002:80"
    volumes:
      - "openbooks-data:/books"
    restart: unless-stopped

  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: oznu/cloudflare-ddns:latest
    environment:
      - API_KEY=
      - ZONE=jwr.ski
      - SUBDOMAIN=home
      - PROXIED=false
    

volumes:
    portainer_data:
    adguard-data:
            external: true
    adguard-config:
            external: true
    openbooks-data:

