version "3.8"

services:
  n8n:
    container_name: n8n
    image: n8nio/n8n:latest-rpi      
    ports:
      - "5678:5678/tcp"
      - "5678:5678/udp"
    volumes:
      - "n8n:/home/node/.n8n"

volumes:
  n8n:
